Develop
kbase/search pull request #7
Opened 2016-12-20 23:32 UTC by qzzhang

Added three plugins for taxonomy, new genomes and genome_features.

2016-12-20 23:38 UTC, kkellerlbl requested changes
I think the tab->space issue in the Makefile should be fixed.  Other than that, everything seems okay, though I haven't worked with these files enough to know for sure.  (Edit: with the .json files that is.)

2016-12-20 23:38 UTC, kkellerlbl commented on Makefile
> +        echo Nothing to do--no compilation steps.
Have these tabs been converted to spaces?  For most files that's okay but in a Makefile they need to be tabs.  (Same for the rest of the diffs listed for Makefile.)

2016-12-20 23:38 UTC, kkellerlbl commented on src/dataExtraction/wsLoad/csFlatFiles_to_ws.py
These modules are no longer needed?  (I'm not sure this script is used any more anyway so it may be irrelevant.)

2016-12-20 23:38 UTC, kkellerlbl commented
Have the changes in the json files been tested anywhere?

2016-12-21 02:45 UTC, qzzhang commented on Makefile
> +        echo Nothing to do--no compilation steps.
They might have been converted by my text editor which I set the tab to be 8 spaces. Should I fix them?

2016-12-21 02:45 UTC, qzzhang commented on src/dataExtraction/wsLoad/csFlatFiles_to_ws.py
I did not touch this file at all.

2016-12-21 16:19 UTC, qzzhang commented
I have made the changes requested.  Please review one more time and let me know if more changes are needed.

2016-12-21 19:25 UTC, kkellerlbl requested changes
One more question about csFlatFiles_to_ws.py.

2016-12-21 19:25 UTC, kkellerlbl commented on src/dataExtraction/wsLoad/csFlatFiles_to_ws.py
Do you or anyone else use this script?  It may be deprecated.  If it is I won't worry about this diff.

2016-12-21 19:25 UTC, kkellerlbl requested changes
Actually, a second question: have these changes been tested anywhere locally?  (That's not a requirement right now, I am just curious.)

2016-12-21 19:30 UTC, kkellerlbl commented
Closing; Qizhi will create a new PR.

2016-12-21 19:30 UTC, closed without merging